# Generated by Django 4.2.1 on 2023-07-07 16:44

from django.db import migrations, models
import django.db.models.deletion
import tasks.models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TasksItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateTimeField(default=tasks.models.one_week_hence)),
            ],
            options={
                "ordering": ["due_date"],
            },
        ),
        migrations.RenameModel(
            old_name="ToDoList",
            new_name="TasksList",
        ),
        migrations.DeleteModel(
            name="ToDoItem",
        ),
        migrations.AddField(
            model_name="tasksitem",
            name="tasks_list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tasks.taskslist"
            ),
        ),
    ]
